version: '3.9'

volumes:
  files_db:


services:
  api:
    image: ntdesmond/ppfs:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    volumes:
      - ./ppfs.yaml:/etc/ppfs.yaml:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mongodb
    logging:
      driver: json-file
      options:
        max-size: 1G

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PPFS_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PPFS_MONGODB_PASSWORD}
    restart: unless-stopped
    volumes:
      - files_db:/data/db:rw
    logging:
      driver: none
