version: '3.9'

services:
  api:
    image: ntdesmond/ppfs:latest
    build:
      dockerfile: ./docker/Dockerfile
      context: ./
    environment:
      - PPFS_JWT_KEY
      - PPFS_MONGODB_USERNAME
      - PPFS_MONGODB_PASSWORD
      - PPFS_ALLOW_REGISTER
      - PPFS_DEFAULT_ADMIN_USERNAME
      - PPFS_DEFAULT_ADMIN_PASSWORD
      - PPFS_DEFAULT_USER_USERNAME
      - PPFS_DEFAULT_USER_PASSWORD
      - PPFS_MONGODB_HOST=mongodb
    ports:
      - "8000:8000"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1G

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PPFS_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PPFS_MONGODB_PASSWORD}
    restart: unless-stopped
    logging:
      driver: none